# api 1

GET http://localhost:3000/todos/?status=TO%20DO
### scenario 1

GET http://localhost:3000/todos/?priority=HIGH
### scenario 2

GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS
### scenario 3

GET http://localhost:3000/todos/?search_q=Buy
### scenario 4

GET http://localhost:3000/todos/?category=WORK&status=DONE
### scenario 5

GET http://localhost:3000/todos/?category=HOME
### scenario 6

GET http://localhost:3000/todos/?category=LEARNING&priority=HIGH
### scenario 7

# api 2
GET http://localhost:3000/todos/6
###

# api 3
GET http://localhost:3000/agenda/?date=2021-11-12
###

# api 4
POST http://localhost:3000/todos/
Content-Type: application/json

{
 "id": 6,
 "todo": "Finalize event theme",
 "priority": "LOW",
 "status": "TO DO",
 "category": "HOME",
 "dueDate": "2021-02-22"
}
###

# api 5
PUT http://localhost:3000/todos/1
Content-Type: application/json

{ "status": "DONE" }
### scenario 1

PUT http://localhost:3000/todos/1
Content-Type: application/json

{ "priority": "HIGH" }
### scenario 2

PUT http://localhost:3000/todos/1
Content-Type: application/json

{"todo": "Clean the garden"}
### scenario 3

PUT http://localhost:3000/todos/1
Content-Type: application/json

{ "category": "LEARNING" }
### scenario 4

PUT http://localhost:3000/todos/1
Content-Type: application/json

{ "dueDate": "2021-01-12" }
### scenario 5

# api 6
DELETE http://localhost:3000/todos/7